version: 2
updates:
  - package-ecosystem: "uv"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"
